#!/usr/bin/env python3
"""
compiler/transcript_loader.py

C47: transcript-driven script ingestion.

For videos whose manifest sets ``transcript_source``, the narration script is
NOT generated by the LLM. It is built verbatim from a marked transcript file
stored under ``compiler/transcripts/``. Beat markers look like::

    [B02 demo — comment block skeleton]
    Now, jumping right into our best practice, ...

The text between markers is FIXED: no additions, no deletions, no paraphrase.
The fidelity invariant: the concatenation of all beat texts must equal the
transcript body (whitespace/punctuation-normalized compare). Coverage is
logged at load as ``wsda-fidelity: coverage=100%``.

Each transcript beat maps onto the existing ``ScriptBeat`` structure
(kind, text, action) so every downstream stage — per-beat TTS, choreography
planning, the seam contract, the park watchdog, rendering, and the gates —
works unchanged. The per-marker action map below is the teaching order and
drives the vision agent.
"""

from __future__ import annotations

import difflib
import re
import sys
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple

from .narrator import ScriptBeat

# ---------------------------------------------------------------------------
# Transcript model
# ---------------------------------------------------------------------------

BEAT_MARKER_RE = re.compile(r"^\[(B\d{2})\s+([^\]]+)\]\s*$")

# Transcript label word -> ScriptBeat kind. "explore" beats (B04-B06) are a
# C47 capability: exploration is content, not a cutaway.
KIND_MAP = {
    "opening": "opening",
    "demo": "demo",
    "explore": "explore",
    "validation": "validation",
    "takeaway": "concept",
    "close": "close",
}


@dataclass
class TranscriptBeat:
    """One marked beat from a transcript file."""

    marker: str
    label: str
    kind: str
    text: str


def parse_transcript(text: str) -> List[TranscriptBeat]:
    """Parse marked beats out of a transcript body."""
    beats: List[TranscriptBeat] = []
    current_marker: Optional[str] = None
    current_label = ""
    body_lines: List[str] = []

    def _flush() -> None:
        if current_marker is None:
            return
        body = " ".join(line.strip() for line in body_lines).strip()
        label_word = current_label.split()[0].lower() if current_label.strip() else "demo"
        kind = KIND_MAP.get(label_word, "demo")
        beats.append(
            TranscriptBeat(
                marker=current_marker,
                label=current_label,
                kind=kind,
                text=body,
            )
        )

    for line in text.split("\n"):
        match = BEAT_MARKER_RE.match(line.strip())
        if match:
            _flush()
            current_marker = match.group(1)
            current_label = match.group(2).strip()
            body_lines = []
        elif current_marker is not None:
            body_lines.append(line)
    _flush()
    return beats


def normalize_fidelity_text(text: str) -> str:
    """Whitespace/punctuation normalization for the fidelity compare."""
    text = text.replace("\u2014", "-").replace("\u2013", "-")
    text = re.sub(r"\s+", " ", text)
    # Normalize spaced punctuation so typographic variance cannot mask drift.
    text = re.sub(r"\s+([,.;:!?])", r"\1", text)
    return text.strip()


def transcript_body_text(parsed: List[TranscriptBeat]) -> str:
    """The transcript body a parser saw: beat texts joined with a single space."""
    return " ".join(b.text for b in parsed)


def fidelity_coverage(beat_texts: List[str], transcript_text: str) -> float:
    """
    Return the share (0-100) of the transcript covered by the beat texts.

    100.0 means the concatenation of the beat texts equals the transcript body
    under whitespace/punctuation normalization — nothing added, nothing lost.
    """
    beats_norm = normalize_fidelity_text(" ".join(t for t in beat_texts if t.strip()))
    transcript_norm = normalize_fidelity_text(transcript_text)
    if not transcript_norm:
        return 0.0
    if beats_norm == transcript_norm:
        return 100.0
    return round(100.0 * difflib.SequenceMatcher(None, beats_norm, transcript_norm).ratio(), 1)


# ---------------------------------------------------------------------------
# C47 beat action map (Walter's 04_04, "first query" lesson)
# ---------------------------------------------------------------------------
#
# Teaching order = action order. B07 composes FROM FIRST below the comment
# block; B09 is the insert-above primitive: SELECT is inserted at the line
# above the FROM clause, not appended. The final editor content is the C46
# blank-free canonical block:
#
#   /*
#   Created By: Walter Shields
#   Create Date: <record date>
#   Description: customer first and last names with email addresses
#   */
#   SELECT FirstName,
#     LastName,
#     Email
#   FROM Customer;


def _record_date(record_date: Optional[str] = None) -> str:
    """Return the Create Date line content: month, followed by day, year."""
    if record_date:
        return record_date
    today = date.today()
    return f"{today.strftime('%B')} {today.day}, {today.year}"


def video_1_1_04_04_actions(record_date: Optional[str] = None) -> Dict[str, Optional[Dict[str, Any]]]:
    """Return the C47 per-marker action map for video_1_1_04_04."""
    create_date = _record_date(record_date)
    return {
        # Open Tab / new SQL tab control (leftmost tab-area icon).
        "B01": {
            "type": "click",
            "detail": "the Open Tab button, the leftmost icon in the SQL tab area, which opens a brand new SQL tab",
        },
        # Comment block skeleton, filled line by line AS NARRATED. The last
        # segment carries no trailing newline so B03 continues the Description
        # line. Screen/narration fidelity: the editor MUST show Walter Shields.
        "B02": {
            "type": "type_segments",
            "segments": [
                {
                    "text": (
                        "/*\n"
                        "Created By: Walter Shields\n"
                        f"Create Date: {create_date}\n"
                        "Description:"
                    )
                }
            ],
        },
        # Description line content + comment close. The leading space keeps the
        # segment on the same line as "Description:" (insert continuation, not
        # a new line).
        "B03": {
            "type": "type_segments",
            "segments": [
                {"text": " customer first and last names with email addresses"},
                {"text": "\n*/"},
            ],
        },
        # Database Structure tab; the table-list tour is choreography.
        "B04": {"type": "click", "detail": "the Database Structure tab"},
        # Expand the Customer table node in the schema tree.
        "B05": {
            "type": "click",
            "detail": "the expansion arrow next to the Customer table in the database structure tree",
        },
        # Browse Data: open the tab, select the Customer table.
        "B06": {
            "type": "sequence",
            "actions": [
                {"type": "click", "detail": "the Browse Data tab"},
                {
                    "type": "click",
                    "detail": "the Customer table in the table selector drop-down on the Browse Data toolbar",
                },
            ],
        },
        # FROM FIRST: insert the FROM clause BELOW the comment block (no
        # SELECT exists yet). The line-paste cadence leaves room for the
        # editor's completion popup to appear while "Customer" lands.
        "B07": {
            "type": "insert_segments",
            "detail": "insert the FROM Customer; clause on the line below the comment block",
            "anchor": "*/",
            "position": "below",
            "segments": [{"text": "FROM Customer;"}],
        },
        # IntelliSense beat: if the completion popup is present, hover/dismiss
        # it; if it never appeared, keep the beat as editor hover + clause
        # review (absence is logged, never faked).
        "B08": {
            "type": "intellisense_review",
            "detail": "review the FROM Customer; clause and dismiss the completion popup if one is open",
            "anchor": "FROM Customer;",
        },
        # INSERT-ABOVE: SELECT is inserted at the line ABOVE the FROM clause,
        # one column per line with commas, as narrated.
        "B09": {
            "type": "insert_segments",
            "detail": "insert the SELECT column list on the lines above the FROM clause",
            "anchor": "FROM Customer;",
            "position": "above",
            "segments": [
                {"text": "SELECT FirstName,"},
                {"text": "  LastName,"},
                {"text": "  Email"},
            ],
        },
        # Execute All; fresh-results verification applies as usual.
        "B10": {
            "type": "run_query",
            "statement": "SELECT FirstName,\n  LastName,\n  Email\nFROM Customer;",
        },
        # Hover the results grid, then the Messages pane ("60 rows returned").
        "B11": {"type": "summarize_result_pane"},
        # Slow summary tour: editor -> results -> messages (choreography only).
        "B12": None,
        # Cursor rests on the finished query (close anchor = SELECT line).
        "B13": None,
    }


def action_map_for(transcript_source: str, record_date: Optional[str] = None) -> Dict[str, Optional[Dict[str, Any]]]:
    """Return the per-marker action map registered for a transcript source."""
    name = Path(transcript_source).stem
    if name == "video_1_1_04_04":
        return video_1_1_04_04_actions(record_date)
    return {}


# ---------------------------------------------------------------------------
# Beat building + fidelity
# ---------------------------------------------------------------------------


def resolve_transcript_path(source: str) -> Path:
    """Resolve a manifest transcript_source (compiler-relative or absolute)."""
    path = Path(source)
    if path.is_absolute():
        return path
    return Path(__file__).resolve().parent / path


def build_transcript_beats(
    transcript_source: str,
    record_date: Optional[str] = None,
) -> Tuple[List[ScriptBeat], float]:
    """
    Build ScriptBeats verbatim from a marked transcript.

    Returns (beats, coverage_pct). Prints the wsda-fidelity line at load; the
    caller hard-fails when coverage is below 100.
    """
    path = resolve_transcript_path(transcript_source)
    parsed = parse_transcript(path.read_text(encoding="utf-8"))
    if not parsed:
        raise ValueError(f"transcript {path} contains no marked beats")
    actions = action_map_for(transcript_source, record_date)
    beats: List[ScriptBeat] = [
        ScriptBeat(
            beat_id=beat.marker,
            kind=beat.kind,
            text=beat.text,
            action=actions.get(beat.marker),
        )
        for beat in parsed
    ]
    coverage = fidelity_coverage([b.text for b in beats], transcript_body_text(parsed))
    print(f"wsda-fidelity: coverage={coverage:.1f}% beats={len(beats)} source={path.name}", file=sys.stderr)
    return beats, coverage


def beats_fidelity_against_source(beats: List[ScriptBeat], transcript_source: str) -> float:
    """Re-check loaded/persisted beat texts against the transcript source."""
    path = resolve_transcript_path(transcript_source)
    parsed = parse_transcript(path.read_text(encoding="utf-8"))
    return fidelity_coverage([b.text for b in beats], transcript_body_text(parsed))
